version: "3"

networks:
  observability:

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./.grafana:/var/lib/grafana
    networks:
      - observability

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./.loki:/etc/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - observability

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - observability

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./.prometheus/etc:/etc/prometheus
      - ./.prometheus/data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

    ports:
      - "9090:9090"
    networks:
      - observability
