version: "3"

networks:
  observability:

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./.grafana:/var/lib/grafana
    networks:
      - observability

  loki:
    image: grafana/loki:2.0.0
    ports:
      - "3100:3100"
    volumes:
      - ./.loki:/etc/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - observability
