global:
  scrape_interval: 5s
  scrape_timeout: 5s

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - "host.docker.internal:5001"
          - "host.docker.internal:6001"
          - "host.docker.internal:7001"
