{
 "title": "Currency Services Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Request Duration",
   "type": "graph",
   "gridPos": { "h": 15, "w": 14, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum without (code) (\n  rate(http_request_duration_seconds_sum[1m])\n  /\n  rate(http_request_duration_seconds_count[1m])\n)",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "Log Entries Written",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate({domain=\"currency\"}[$__interval])) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Number of HTTP Requests by Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (code) (increase(http_requests_received_total[1m]))",
     "legendFormat": "Http Status {{code}}"
    }
   ]
  },
  {
   "title": "Total Number of HTTP Requests",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (exported_job) (http_requests_received_total)",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "HTTP Requests in Progress",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "http_requests_in_progress", "legendFormat": "{{exported_job}}" }
   ]
  }
 ]
}